name: Build and Deploy Full Demo to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "full-demo/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./full-demo
        run: |
          npm ci || npm install

      - name: Build
        working-directory: ./full-demo
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./full-demo/dist
          publish_branch: gh-pages
